import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/component/for-header/Header";
import Head from "next/head";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  display: "swap", // ✅ แนะนำให้เพิ่ม
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  display: "swap", // ✅ แนะนำให้เพิ่ม
});

export const metadata: Metadata = {
  title: "Happybon",
  description: "Generated by create next app",
  icons: {
    icon: "/logoheader.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <Head>
        <title>Happybon</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logoheader.png" type="image/png" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="anonymous"
        />
      </Head>
      <body cz-shortcut-listen="true">
        <div className="overflow-x-hidden">
          <Header />
        </div>
        {children}
      </body>
    </html>
  );
}
